author:
  email: devinhedge@gmail.com
  homepage: https://github.com/devinhedge
  name: Devin Hedge
description: Holiday API Custom Component for Home Assistant.
files:
- custom_components/blueprint/__init__.py
- custom_components/blueprint/const.py
- custom_components/blueprint/binary_sensor.py
- custom_components/blueprint/sensor.py
- custom_components/blueprint/switch.py
keywords:
- holidayapi
- homeassistant
- home-assistant
- custom-component
- python
license: MIT License
name: holidayapi
type: component
